# Generated by Django 5.1.2 on 2024-10-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], default='2025', max_length=4)),
                ('major', models.CharField(choices=[('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('Applied Physics', 'Applied Physics'), ('Art History', 'Art History'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Classics', 'Classics'), ('Communication', 'Communication'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Elementary Education', 'Elementary Education'), ('Environmental Geoscience', 'Environmental Geoscience'), ('Environmental Studies', 'Environmental Studies'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German Studies', 'German Studies'), ('Global Public Health and the Common Good (CSON)', 'Global Public Health and the Common Good (CSON)'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Human-Centered Engineering', 'Human-Centered Engineering'), ('Independent Major', 'Independent Major'), ('International Studies', 'International Studies'), ('Islamic Civilization and Societies', 'Islamic Civilization and Societies'), ('Italian', 'Italian'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Management (CSOM)', 'Management (CSOM)'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Russian', 'Russian'), ('Slavic Studies', 'Slavic Studies'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology')], default='Computer Science', max_length=100)),
                ('minor', models.CharField(choices=[('N/A', 'N/A'), ('Ancient Greek', 'Ancient Greek'), ('Arabic Studies', 'Arabic Studies'), ('Art History', 'Art History'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Chinese', 'Chinese'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German', 'German'), ('Global Public Health and Common Good', 'Global Public Health and Common Good'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Italian', 'Italian'), ('Latin', 'Latin'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Music', 'Music'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Russian', 'Russian'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology')], default='N/A', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
