# Generated by Django 5.1.2 on 2024-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='minor',
        ),
        migrations.AddField(
            model_name='student',
            name='major2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('Applied Physics', 'Applied Physics'), ('Art History', 'Art History'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Classics', 'Classics'), ('Communication', 'Communication'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Elementary Education', 'Elementary Education'), ('Environmental Geoscience', 'Environmental Geoscience'), ('Environmental Studies', 'Environmental Studies'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German Studies', 'German Studies'), ('Global Public Health and the Common Good (CSON)', 'Global Public Health and the Common Good (CSON)'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Human-Centered Engineering', 'Human-Centered Engineering'), ('Independent Major', 'Independent Major'), ('International Studies', 'International Studies'), ('Islamic Civilization and Societies', 'Islamic Civilization and Societies'), ('Italian', 'Italian'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Management (CSOM)', 'Management (CSOM)'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Russian', 'Russian'), ('Slavic Studies', 'Slavic Studies'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('N/A', 'N/A'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('Applied Physics', 'Applied Physics'), ('Art History', 'Art History'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Classics', 'Classics'), ('Communication', 'Communication'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Elementary Education', 'Elementary Education'), ('Environmental Geoscience', 'Environmental Geoscience'), ('Environmental Studies', 'Environmental Studies'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German Studies', 'German Studies'), ('Global Public Health and the Common Good (CSON)', 'Global Public Health and the Common Good (CSON)'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Human-Centered Engineering', 'Human-Centered Engineering'), ('Independent Major', 'Independent Major'), ('International Studies', 'International Studies'), ('Islamic Civilization and Societies', 'Islamic Civilization and Societies'), ('Italian', 'Italian'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Management (CSOM)', 'Management (CSOM)'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Russian', 'Russian'), ('Slavic Studies', 'Slavic Studies'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology')], default='Computer Science', max_length=100),
        ),
    ]
