# Generated by Django 5.1.2 on 2024-10-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_minor_student_major2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('MCAS', 'MCAS'), ('CSOM', 'CSOM'), ('CSON', 'CSON'), ('LSEHD', 'LSEHD'), ('MESSINA', 'MESSINA')], default='2025', max_length=100),
        ),
    ]
