# Generated by Django 5.1.2 on 2024-10-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_student_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.CharField(
                choices=[
                    ("MCAS", "MCAS"),
                    ("CSOM", "CSOM"),
                    ("CSON", "CSON"),
                    ("LSEHD", "LSEHD"),
                    ("MESSINA", "MESSINA"),
                ],
                default="MCAS",
                max_length=100,
            ),
        ),
    ]
