# Generated by Django 5.1.2 on 2024-10-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_campaign_alter_student_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for the campaign",
                null=True,
                upload_to="campaign_images/",
            ),
        ),
    ]
