# Generated by Django 5.1.2 on 2024-10-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_school'),
        ('users', '0009_campaign_points'),
    ]

    operations = [
    ]
