# Generated by Django 5.1.2 on 2024-10-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_campaign_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the reward title', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the reward')),
                ('points_required', models.PositiveIntegerField(help_text='Number of points required to redeem')),
                ('available_from', models.DateField(help_text='Reward available from this date')),
                ('available_until', models.DateField(help_text='Reward available until this date')),
            ],
            options={
                'ordering': ['available_from'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='points_balance',
            field=models.IntegerField(default=0, help_text="Student's current points balance"),
        ),
        migrations.CreateModel(
            name='RewardExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_redeemed', models.DateField(auto_now_add=True)),
                ('points_used', models.PositiveIntegerField()),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='users.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_exchanges', to='users.student')),
            ],
            options={
                'ordering': ['-date_redeemed'],
            },
        ),
    ]
