# Generated by Django 5.1.2 on 2024-10-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_0007_alter_student_school_0009_campaign_points'),
        ('users', '0010_reward_student_points_balance_rewardexchange'),
    ]

    operations = [
    ]
