# Generated by Django 5.1.2 on 2024-11-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20241030_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_daily_challenge', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='action_photos/')),
                ('date_completed', models.DateTimeField()),
                ('points_earned', models.PositiveIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.action')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_actions', to='users.student')),
            ],
        ),
    ]
