# Generated by Django 5.1.2 on 2024-11-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_action_completedaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedaction',
            name='photo',
            field=models.ImageField(upload_to='completed_actions/'),
        ),
        migrations.AlterField(
            model_name='completedaction',
            name='points_earned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='completedaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
