# Generated by Django 5.1.2 on 2024-11-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_completedaction_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.campaign'),
        ),
    ]
