# Generated by Django 5.1.2 on 2024-11-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_action_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='completedaction',
            name='photo',
            field=models.ImageField(upload_to='action_photos/'),
        ),
        migrations.AlterField(
            model_name='completedaction',
            name='points_earned',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='completedaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_actions', to='users.student'),
        ),
    ]
