# Generated by Django 5.1.2 on 2024-11-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_action_campaign_alter_completedaction_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedaction',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.campaign'),
        ),
    ]
