# Generated by Django 5.1.2 on 2024-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_reward_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_campaigns',
            field=models.JSONField(default=list, help_text='List of campaigns the student has completed'),
        ),
    ]
