# Generated by Django 5.1.2 on 2024-12-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_student_completed_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='leaderboard_points',
            field=models.IntegerField(blank=True, default=0, help_text="Student's total points balance"),
        ),
        migrations.AlterField(
            model_name='student',
            name='completed_campaigns',
            field=models.JSONField(blank=True, default=list, help_text='List of campaigns the student has completed'),
        ),
        migrations.AlterField(
            model_name='student',
            name='points_balance',
            field=models.IntegerField(blank=True, default=0, help_text="Student's current points balance"),
        ),
    ]
