databases:
- name: sweeatzdb
plan: free
databaseName: sweeatz
user: sweeatz_user
services:
- type: web
plan: free
name: sweeatz
runtime: python
buildCommand: "./build.sh"
startCommand: "gunicorn SWEeatz.wsgi"
envVars:
- key: DATABASE_URL
fromDatabase:
name: sweeatzdb
property: connectionString
- key: SECRET_KEY
generateValue: true